version: '3.8'
services:
  jersey:
    build:
      context: .
    volumes:
    - /app/target
    - .:/app
    ports:
    - '8080:8080'
    environment:
      - LOG_LEVEL=DEBUG
    command: ./mvnw exec:java